// <auto-generated />
using System;
using Civica.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Civica.Api.Migrations
{
    [DbContext(typeof(CivicaDbContext))]
    [Migration("20251129141041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Civica.Api.Models.Domain.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AchievementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("RequirementData")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("RewardBadgeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementType");

                    b.HasIndex("RewardBadgeId");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AchievementType = "issues_reported",
                            CreatedAt = new DateTime(2025, 11, 29, 14, 10, 40, 989, DateTimeKind.Utc).AddTicks(6062),
                            Description = "Report your first issue",
                            IsActive = true,
                            MaxProgress = 1,
                            RequirementData = "{\"target\": 1}",
                            RewardBadgeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RewardPoints = 50,
                            Title = "First Steps"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AchievementType = "issues_reported",
                            CreatedAt = new DateTime(2025, 11, 29, 14, 10, 40, 989, DateTimeKind.Utc).AddTicks(6172),
                            Description = "Report 10 issues",
                            IsActive = true,
                            MaxProgress = 10,
                            RequirementData = "{\"target\": 10}",
                            RewardPoints = 200,
                            Title = "Community Champion"
                        });
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.AdminAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("AdminSupabaseId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstimatedResolutionTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("IssueId");

                    b.ToTable("AdminActions");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.Authority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("City", "District");

                    b.ToTable("Authorities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            City = "București",
                            County = "București",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pmb@pmb.ro",
                            IsActive = true,
                            Name = "Primăria Municipiului București"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000002"),
                            City = "București",
                            County = "București",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Sector 1",
                            Email = "primarie@primarias1.ro",
                            IsActive = true,
                            Name = "Primăria Sectorului 1 București"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000003"),
                            City = "București",
                            County = "București",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Sector 2",
                            Email = "primarie@ps2.ro",
                            IsActive = true,
                            Name = "Primăria Sectorului 2 București"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000004"),
                            City = "București",
                            County = "București",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Sector 3",
                            Email = "primarie@primarie3.ro",
                            IsActive = true,
                            Name = "Primăria Sectorului 3 București"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000005"),
                            City = "București",
                            County = "București",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Sector 4",
                            Email = "primarie@ps4.ro",
                            IsActive = true,
                            Name = "Primăria Sectorului 4 București"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000006"),
                            City = "București",
                            County = "București",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Sector 5",
                            Email = "primarie@sector5.ro",
                            IsActive = true,
                            Name = "Primăria Sectorului 5 București"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000007"),
                            City = "București",
                            County = "București",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Sector 6",
                            Email = "primarie@primarie6.ro",
                            IsActive = true,
                            Name = "Primăria Sectorului 6 București"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000001"),
                            City = "Cluj-Napoca",
                            County = "Cluj",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "primarie@primariaclujnapoca.ro",
                            IsActive = true,
                            Name = "Primăria Municipiului Cluj-Napoca"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000002"),
                            City = "Timișoara",
                            County = "Timiș",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "primarie@primariatm.ro",
                            IsActive = true,
                            Name = "Primăria Municipiului Timișoara"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000003"),
                            City = "Iași",
                            County = "Iași",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "primarie@primaria-iasi.ro",
                            IsActive = true,
                            Name = "Primăria Municipiului Iași"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000004"),
                            City = "Constanța",
                            County = "Constanța",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "primarie@primaria-constanta.ro",
                            IsActive = true,
                            Name = "Primăria Municipiului Constanța"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000005"),
                            City = "Brașov",
                            County = "Brașov",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "primarie@brasovcity.ro",
                            IsActive = true,
                            Name = "Primăria Municipiului Brașov"
                        });
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Common");

                    b.Property<string>("RequirementDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RequirementType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("RequirementValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Rarity");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Starter",
                            CreatedAt = new DateTime(2025, 11, 29, 14, 10, 40, 988, DateTimeKind.Utc).AddTicks(9125),
                            Description = "Reported your first community issue",
                            IconUrl = "/assets/badges/civic-starter.svg",
                            IsActive = true,
                            Name = "Civic Starter",
                            Rarity = "Common",
                            RequirementDescription = "Report your first issue",
                            RequirementType = "issues_reported",
                            RequirementValue = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Progress",
                            CreatedAt = new DateTime(2025, 11, 29, 14, 10, 40, 988, DateTimeKind.Utc).AddTicks(9190),
                            Description = "Uploaded high-quality photos with your report",
                            IconUrl = "/assets/badges/picture-perfect.svg",
                            IsActive = true,
                            Name = "Picture Perfect",
                            Rarity = "Uncommon",
                            RequirementDescription = "Upload 3 high-quality photos",
                            RequirementType = "quality_photos",
                            RequirementValue = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Progress",
                            CreatedAt = new DateTime(2025, 11, 29, 14, 10, 40, 988, DateTimeKind.Utc).AddTicks(9193),
                            Description = "Voted on 10 community issues",
                            IconUrl = "/assets/badges/community-voice.svg",
                            IsActive = true,
                            Name = "Community Voice",
                            Rarity = "Common",
                            RequirementDescription = "Vote on 10 issues",
                            RequirementType = "community_votes",
                            RequirementValue = 10
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Achievement",
                            CreatedAt = new DateTime(2025, 11, 29, 14, 10, 40, 988, DateTimeKind.Utc).AddTicks(9195),
                            Description = "3 of your issues have been resolved",
                            IconUrl = "/assets/badges/problem-solver.svg",
                            IsActive = true,
                            Name = "Problem Solver",
                            Rarity = "Rare",
                            RequirementDescription = "3 issues resolved",
                            RequirementType = "issues_resolved",
                            RequirementValue = 3
                        });
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AIConfidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("AIGeneratedDescription")
                        .HasColumnType("text");

                    b.Property<string>("AIProposedSolution")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<string>("AssignedDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CommunityImpact")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentSituation")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("DesiredOutcome")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EmailsSent")
                        .HasColumnType("integer");

                    b.Property<int?>("EstimatedImpact")
                        .HasColumnType("integer");

                    b.Property<string>("EstimatedResolutionTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Landmark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<int>("LocationAccuracy")
                        .HasColumnType("integer");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Medium");

                    b.Property<bool>("PublicVisibility")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Submitted");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Medium");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("District");

                    b.HasIndex("EmailsSent")
                        .IsDescending();

                    b.HasIndex("Status");

                    b.HasIndex("Urgency");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "PublicVisibility")
                        .HasFilter("\"Status\" = 'Approved' AND \"PublicVisibility\" = true");

                    b.HasIndex("Status", "PublicVisibility", "CreatedAt")
                        .IsDescending()
                        .HasFilter("\"Status\" = 'Approved' AND \"PublicVisibility\" = true");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.IssueAuthority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CustomName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("IssueId");

                    b.HasIndex("IssueId", "AuthorityId")
                        .IsUnique()
                        .HasFilter("\"AuthorityId\" IS NOT NULL");

                    b.HasIndex("IssueId", "CustomEmail")
                        .IsUnique()
                        .HasFilter("\"CustomEmail\" IS NOT NULL");

                    b.ToTable("IssueAuthorities", t =>
                        {
                            t.HasCheckConstraint("CK_IssueAuthority_AuthorityOrCustom", "(\"AuthorityId\" IS NOT NULL AND \"CustomName\" IS NULL AND \"CustomEmail\" IS NULL) OR (\"AuthorityId\" IS NULL AND \"CustomName\" IS NOT NULL AND \"CustomEmail\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.IssuePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("FileSize")
                        .HasColumnType("integer");

                    b.Property<string>("Format")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Medium");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IssueId");

                    b.ToTable("IssuePhotos");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.HasIndex("Completed", "CompletedAt");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("EarnedAt")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AchievementsEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ApprovalRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("City")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("București");

                    b.Property<int>("CommentsGiven")
                        .HasColumnType("integer");

                    b.Property<bool>("CommunityNewsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("CommunityVotes")
                        .HasColumnType("integer");

                    b.Property<string>("County")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("București");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentLoginStreak")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentVotingStreak")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("District")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Sector 5");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("HelpfulComments")
                        .HasColumnType("integer");

                    b.Property<bool>("IssueUpdatesEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("IssuesReported")
                        .HasColumnType("integer");

                    b.Property<int>("IssuesResolved")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("LongestLoginStreak")
                        .HasColumnType("integer");

                    b.Property<int>("LongestVotingStreak")
                        .HasColumnType("integer");

                    b.Property<bool>("MonthlyDigestEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("QualityScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ResidenceType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SupabaseUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("District");

                    b.HasIndex("Email");

                    b.HasIndex("Level")
                        .IsDescending();

                    b.HasIndex("Points")
                        .IsDescending();

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.Achievement", b =>
                {
                    b.HasOne("Civica.Api.Models.Domain.Badge", "RewardBadge")
                        .WithMany()
                        .HasForeignKey("RewardBadgeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RewardBadge");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.AdminAction", b =>
                {
                    b.HasOne("Civica.Api.Models.Domain.UserProfile", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Civica.Api.Models.Domain.Issue", "Issue")
                        .WithMany("AdminActions")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.Issue", b =>
                {
                    b.HasOne("Civica.Api.Models.Domain.UserProfile", "User")
                        .WithMany("Issues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.IssueAuthority", b =>
                {
                    b.HasOne("Civica.Api.Models.Domain.Authority", "Authority")
                        .WithMany("IssueAuthorities")
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Civica.Api.Models.Domain.Issue", "Issue")
                        .WithMany("IssueAuthorities")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.IssuePhoto", b =>
                {
                    b.HasOne("Civica.Api.Models.Domain.Issue", "Issue")
                        .WithMany("Photos")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.UserAchievement", b =>
                {
                    b.HasOne("Civica.Api.Models.Domain.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Civica.Api.Models.Domain.UserProfile", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.UserBadge", b =>
                {
                    b.HasOne("Civica.Api.Models.Domain.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Civica.Api.Models.Domain.UserProfile", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.Authority", b =>
                {
                    b.Navigation("IssueAuthorities");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.Issue", b =>
                {
                    b.Navigation("AdminActions");

                    b.Navigation("IssueAuthorities");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Civica.Api.Models.Domain.UserProfile", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserBadges");
                });
#pragma warning restore 612, 618
        }
    }
}
